version: "3.9"
   
services:
  gdb:
    build:
      context: "."
      dockerfile: "Dockerfile.gdb"
    volumes:
      - ./data:/code
      - shared-tmpfs:/app

  jdwp:
    build: .
    volumes:
      - ./data:/code
      - shared-tmpfs:/app
    ports:
      - "8000:8000"

volumes:
  shared-tmpfs:
    driver: local
    driver_opts:
      device: tmpfs
      type: tmpfs
      o: "size=256m,uid=1000"