version: "3.9"
   
services:
  gdb:
    build:
      context: "."
      dockerfile: "Dockerfile.gdb"
    volumes:
      - .:/code
      - static:/app/priv/static

  jdwp:
    build: .
    volumes:
      - .:/code
      - static:/app/priv/static
    ports:
      - "8000:8000"
    depends_on:
      - gdb

volumes:
  static:
    driver_opts:
      device: tmpfs
      type: tmpfs